name: Quasar CI CD

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - ".vscode/**"
      - "README.md"

  pull_request:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - ".vscode/**"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-20.04

    permissions:
      id-token: write
      contents: read
      pages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install & npm install -g @quasar/cli

      - name: Build
        run: npm run build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/spa
